### ISSUE TITLE
Option for changing the default camera

### ISSUE THREAD

**Issue by srivatsanpp** [karayaman/Play-online-chess-with-real-chess-board#1]
Hi Karayaman,

Thank you for the great program. I am trying to play through this. It is good option to avoid screen and play with real chess board!

One input - I used Droidcam to use mobile camera. But one problem is that the board calibration program uses only the default camera. For now, I disabled the windows camera and the program identified the Droidcam. It would be good if you have option to set the camera for using.

Thanks,
Srivatsan

**Comment by Kacnep87** [comment]
@srivatsanpp, as i know (im testing Alper's program too), program do not use only default webcam on your pc/laptop. Im using Trust Webcam on my desktop PC and on my laptop (integrated webcam is disabled at this moment). But i do not know why, but after i downloaded version 1.8 no one webcam is not working on my laptop. Im very surptised with that. I re-downloaded it back to 1.7 version, but still not working.

**Comment by karayaman** [comment]
Hi Srivatsan,
You are welcome. Option for changing the default camera is added to the GUI. You can use this option with release v1.9 which is recently published.
