### ISSUE TITLE
Write PGNs?

### ISSUE THREAD

**Issue by kyleboddy** [karayaman/Play-online-chess-with-real-chess-board#10]
Can this app simply write to PGN instead of playing online?

**Comment by karayaman** [comment]
Hello, it can't do that in a simple way. However, you can record your over the board games by enabling "Make moves of opponent too." option in the GUI. You can check this video to see how this option works [Test of automatic recording of DGT Centaur games](https://www.youtube.com/watch?v=j7apOxAJeO8) The chess GUI you are using probably have the option to export PGN.

**Comment by kyleboddy** [comment]
Basically I'd like to play against no opponent - the Analysis Board being recognized as a game would be helpful, so I can just play OTB with a friend and all the moves get mirrored on lichess and then save to PGN rather than play someone on lichess. I can simulate this by making two accounts and just playing the moves using the "Make moves of opponent too" and playing a game but that's somewhat cumbersome.

I'll look at the source code and see if the API can make moves on the Analysis board too.
