### ISSUE TITLE
Hello Can you tell me which version of python are you using

### ISSUE THREAD

**Issue by xxvenomous** [karayaman/Play-online-chess-with-real-chess-board#11]
Hello, I'm on an old mac with Sierra, I've installed it once but due an accident i deleted the virtualenv.
Can you tell me wich version of python are you using anf which version of the package requirements?
Thanks in advance.

**Comment by karayaman** [comment]
Hello, it should work fine with latest versions of Python and required packages. The Python version I am using is 3.9.6 Below are the versions of the required packages:
opencv-python 4.5.2.54 
python-chess 1.6.1
pyautogui 0.9.53
mss 6.1.0
numpy 1.21.0
pyttsx3 2.90
scikit-image 0.18.2
pygrabber 0.1
mac-say 2020.12.3
berserk 0.10.0

**Comment by xxvenomous** [comment]
Thanks for the quick reply, there are some dependencies probem with python 3.7 and 3.8 but after 10 hours I has been able to use it. I think I have some problem with the board or the smatphone because i always get the erro "Move registration failed". Last thing, since I am Italian I wrote the class Italian in the languages.py file and I modified the guy.py file adding Italian and it_ to the language and languages lists but with no luck. If you need the translation no problem. 
Thanks again!

**Comment by karayaman** [comment]
You are welcome. I can add support for Italian voices if I know the correct translations of chess terms and sentences listed below.
Game Started - Gioco iniziato
Move registration failed. Please redo your move. - Registrazione spostamento non riuscita. Per favore, rifai la tua mossa.
checkmate - scacco matto
check - scacco
castling short - arrocco corto
castling long - arrocco lungo
Queen a1 takes d4 - La Donna a1 prende d4
Knight f1 to f3 - Cavaliere da f1 a f3
Pawn b7 to b8 promotion to queen - Pedone da b7 a b8 promozione a Donna
Pawn - Pedone
Knight - Cavallo
Bishop - Alfiere
Rook - Torre
Queen - Donna
King - Re
Let me know if any corrections I need to make. Also, do I need to know any special grammar
rule for saying the moves?
If you think there is an error with the program you can copy/paste the log output and send to me via e-mail.

**Comment by xxvenomous** [comment]
It's almost perfect just some minor correction i will write here.
Game Started - Gioco iniziato
Move registration failed. Please redo your move. - Registrazione spostamento non riuscita. Per favore rifai la tua mossa.
checkmate - scacco matto
check - scacco
castling short - arrocco corto
castling long - arrocco lungo
Queen a1 takes d4 - La Regina a1 cattura d4 
Knight f1 to f3 - Cavalllo da f1 a f3 
Pawn b7 to b8 promotion to queen - Pedone da b7 a b8 promuove a Regina
Pawn - Pedone
Knight - Cavallo
Bishop - Alfiere
Rook - Torre
Queen - Regina
King - Re
All you wrote is correct takes we translate to "cattura" and Queen is Regina.
If you need other assistance let me know I'm happy to help.
Regarding.
I will send you a detailed explanation on the problem installing, i will try with other python version and i will send u a log. on mac with sierra. Actually the only option is to use python 3.7.3 and use python-opencv==4.1.20 and downgrade a lot of packages.

**Comment by karayaman** [comment]
I updated the source code with support for Italian voices. Let me know if it works as expected.

**Comment by xxvenomous** [comment]
Hello, the italian voice works perfectly. Sadly since I've tried with several python version the problem is that i can only make ith works with python 3.7.3 and downgrading a lot of packages on macos is a mess and now I don't remember wich vertual enviroment was good. Anyway I've tried today and when i a have to move the white piece doesn't work, instead works if i move the black piece. I'm attaching my configuration I play with say my moves, say opponent moves, find chess board online without template both lichess and chessdotcom and make moves by drag and drop enabled.
Have a nice day.
[python3.7.3.txt](https://github.com/karayaman/Play-online-chess-with-real-chess-board/files/8550159/python3.7.3.txt)

**Comment by xxvenomous** [comment]
Sorry my bad. So The calibration now works but I can't go over 3/4 moves. When using the wired webcamera i can easily rotate the picture and get the proper a8 square using the phone with Iriun Webcam the image is huge and i cant resize the image so i can't see nothing and doesn't work.
I'm attaching the error log just in case.
[chess_error.txt](https://github.com/karayaman/Play-online-chess-with-real-chess-board/files/8550786/chess_error.txt)
Whish you a nice week.

**Comment by karayaman** [comment]
I checked the log files. It seems like it can't detect the change on square e2 when you play 1.e4. Then, you play 1... e5. But it can't register it because it still waits to register the first move of white.

The program has an internal game state, and when you restart, it will reset its internal game state to the starting position.
When you get an error, my suggestion is to undo your move and then wait a couple seconds.

When you use your phone's camera with Iriun Webcam, the image is huge because it shows the calibration result at full resolution. You can lower the image resolution in the settings of Iriun Webcam. Due to the implementation of the program, it is really not necessary to set your resolution to anything higher than 720p (1280X720).
