### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by erwin4u-alt** [karayaman/Play-online-chess-with-real-chess-board#19]
Hello, 
I've installed the code on an Raspi Zero with Bullseye and it looks good so far. I'm able to scan the board, but if I try to start the game, I got an error (see below)
Do you know, how to solve this issue?
I run python (3.9.2) with sudo in an virtual environment - all libraries are installed...

Traceback (most recent call last):
File "/home/pi/Play-online-chess-with-real-chess-board-1.15/main.py", line 10, in <module>
    from board_basics import Board_basics
  File "/home/pi/Play-online-chess-with-real-chess-board-1.15/board_basics.py", line 3, in <module>
    from skimage.metrics import structural_similarity
  File "/usr/local/lib/python3.9/dist-packages/skimage/__init__.py", line 151, in <module>
    from ._shared import geometry
  File "skimage/_shared/geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
Game finished.

**Comment by karayaman** [comment]
Hi, it seems like there is an incompatibility between versions of numpy and scikit-image you are using. You can try reinstalling numpy with
 `pip install --upgrade numpy`
or you can try downgrading scikit-image library to a previous version with
`pip uninstall scikit-image`
`pip install scikit-image==0.19.3`

**Comment by karayaman** [comment]
It seems like there is a problem with simplejson library. Maybe you should uninstall it with
`pip uninstall simplejson`
if that does not work you can try downgrading the version of simplejson. You can pick from it's version history 
https://pypi.org/project/simplejson/#history
for instance:
`pip install simplejson==3.17.0`

**Comment by erwin4u-alt** [comment]
probably this was the issue. I've deleted simplejson and do not get an error message anymore.
Unfortunately the raspi zero crash if I open a game in lichess. Probably the hardware isn't strong enough ...
I'm not sure if it make sense to invest more time in this project with this hardware.
But many thanks for your assistance!!!

**Comment by karayaman** [comment]
You are welcome. Actually, hardware requirements should be really low. But while using it with lichess sometimes communication delay occurs (1-2 seconds most of the time) which results in increased memory usage. Because, it stops processing the frames and stores them in memory until server responds. So, you may get it working with another chess software such as [Lucas Chess](https://lucaschess.pythonanywhere.com/downloads)

**Comment by erwin4u-alt** [comment]
I've installed on my MacBook an it work's well.
Many thanks for this great job!!!
