### ISSUE TITLE
support dark wood boards (like the DGT boards)

### ISSUE THREAD

**Issue by zevaverbach** [karayaman/Play-online-chess-with-real-chess-board#20]
Would you accept a PR to implement this?

**Comment by karayaman** [comment]
Hi, thanks but I wouldn't because they already have their own software.

**Comment by tttiago** [comment]
There are other boards with a dark frame, where OpenCV's `findChessboardCorners` will not work.
Initially, I was using one of these boards and could not complete the board calibration step.
See their note in the [documentation](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#ga93efa9b0aa890de240ca32b11253dd4a): "The function requires white space (like a square-thick border, the wider the better) around the board to make the detection more robust in various environments."

**Comment by zevaverbach** [comment]
@karayaman I was referring to dark-colored boards, not e-boards. I much prefer playing on a nice wooden board, which tend to be darker. I'm surprised you wouldn't want to enable that for your users!
