### ISSUE TITLE
2 Players Real Board

### ISSUE THREAD

**Issue by abhik-creator** [karayaman/Play-online-chess-with-real-chess-board#28]
Plz make option for 2 player Real board option without playing online. So that I can use PGN Online

**Comment by Pbatch** [comment]
Try https://www.camerachess.com if you want to play with 2 players irl

**Comment by karayaman** [comment]
Hi, Lichess only version of this project has this feature visit [Lichess with a real board](https://github.com/karayaman/lichess-with-a-real-board)
