### ISSUE TITLE
Only one game can be played at a time

### ISSUE THREAD

**Issue by andreiarriaza** [karayaman/Play-online-chess-with-real-chess-board#29]
It displays the error that only one game can be played at a time. He asks me to close the other open games. But there is only one game at that time.

**Comment by aligitor** [comment]
It happened to me when I had running correspondence game on the chess site.

**Comment by andreiarriaza** [comment]
Thank you very much for the help, indeed that was one of the problems.

> It happened to me when I had running correspondence game on the chess site.
