### ISSUE TITLE
cant run  "Error creating bean with name 'pendule'"

### ISSUE THREAD

**Issue by 9acca9** [karayaman/Play-online-chess-with-real-chess-board#4]
Hi.
I have this problem. Can you give me a hand to solve?

`Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pendule' defined in URL [jar:file:/home/xxxxxxx/Descargas/webcamChess.jar!/game/chess/graphics/Pendule.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [game.chess.graphics.Pendule]: Constructor threw exception; nested exception is java.lang.NullPointerException
`
Thanks!

**Comment by karayaman** [comment]
Hi, it seems like you have downloaded the wrong software. Here is the link to the latest release of the software: [https://github.com/karayaman/Play-online-chess-with-real-chess-board/releases/tag/v1.10](url) 
You should download and extract "program.zip" in this link. You can find all the releases of the software in this link:
[https://github.com/karayaman/Play-online-chess-with-real-chess-board/releases](url)
