### ISSUE TITLE
webcam selection

### ISSUE THREAD

**Issue by perretd1** [karayaman/Play-online-chess-with-real-chess-board#5]
I'm having difficulty selecting the webcam.  In the gui.py it does have a selector but is only showing 'default' and I am attempting to use a virtual cam client so I can use my phone to point to the board (droidcam on win10) but it not allowing this.  If there  is any input on this I would appreciate it.

**Comment by karayaman** [comment]
Hi, for webcam selection it requires pygrabber library to be installed(https://pypi.org/project/pygrabber/). I just added this library to the required libraries section of README.

**Comment by perretd1** [comment]
Thank you!
By the way, this is brilliant! Very well done
