### ISSUE TITLE
Human vs Human on real Board

### ISSUE THREAD

**Issue by theGreat81** [karayaman/Play-online-chess-with-real-chess-board#7]
Hello, 
Is it possible to add an option for (Human vs. Human) game? I want to play on real board and after that I want to analyze the game.
please add this option then users can play chess on their chess boards like **DGT e-boards**!
thanks a lot for your awesome project.

**Comment by karayaman** [comment]
Hello, this option already exists. You can record your (Human vs. Human) games by enabling "Make moves of opponent too." option in the GUI. You can check this video to see how this option works [Test of automatic recording of DGT Centaur games](https://www.youtube.com/watch?v=j7apOxAJeO8)
